service: mkplace-challenge

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1

plugins:
  - serverless-webpack
  - serverless-offline

package:
  excludeDevDependencies: true
  individually: true

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'
    excludeFiles: src/**/*.test.js

functions:
  index:
    handler: src/functions/products/index.handle
    events:
      - http:
          path: product
          method: get
          cors: true
  getOne:
    handler: src/functions/products/getProduct.handle
    events:
      - http:
          path: product/{id}
          method: get
          cors: true
  create:
    handler: src/functions/products/createProduct.handle
    events:
      - http:
          path: product
          method: post
          cors: true
  update:
    handler: src/functions/products/updateProduct.handle
    events:
      - http:
          path: product/{id}
          method: put
          cors: true